### ISSUE TITLE
Spring 0 - Desarrollo cuarta sección pagina.

### ISSUE THREAD

**Issue by Andresmps** [Andresmps/MiPrimeraWeb-grupo45-05#10]
Sección de equipo: El estudiante deberá dividir el ancho del sitio entre el número de participantes del equipo e incluir junto con cada uno una foto o imagen, el nombre y algún dato como la institución educativa, edad, pasatiempo, entre otros. El elemento donde están los servicios debe de tener un id=”team” .

**Comment by DavidSantiagoPedraza** [comment]
Cerrado
