### ISSUE TITLE
Spring 1 - Preguntar al tutor la entrega del modelo vista-controlador.

### ISSUE THREAD

**Issue by Andresmps** [Andresmps/MiPrimeraWeb-grupo45-05#24]
Sprint 1: Entrega en última clase semana 3
i. Presentación MVC
   1. Interfases gráficas de usuario
   2. Navegación entre interfases

ii. Informe de retrospectiva

**Comment by guzmanjs** [comment]
Se resuelve la duda con el tutor. Queda referenciado que con resolver los requerimientos del Sprint 1 del proyecto se resuelven los requerimiento de MVC.

Adjunto de la conversación: 

![ac8cf7ba-9366-4021-847d-7e403458c069](https://user-images.githubusercontent.com/86807757/134043859-07ae0de0-1d2f-454a-903b-6350bc63b431.jpg)
