### ISSUE TITLE
Spring 1 - Creación de mock-up a partir de las secciones realizadas.

### ISSUE THREAD

**Issue by Andresmps** [Andresmps/MiPrimeraWeb-grupo45-05#26]

**Comment by guzmanjs** [comment]
Se hace la unión de las distintas partes construídas del mock up en un solo gráfico y se modifica para mostrar las secciones actuales. 

![Mockup-Iservi](https://user-images.githubusercontent.com/86807757/134044084-a1c9cfab-247e-4ada-97ef-1ef045cf4382.png)
